In [65]:
!pip show pandas
# show info on pandas library
# if no pandas library -> install using pip install pandas

Name: pandas
Version: 2.2.2
Summary: Powerful data structures for data analysis, time series, and statistics
Home-page: https://pandas.pydata.org
Author:
Author-email: The Pandas Development Team <pandas-dev@python.org>
License: BSD 3-Clause License

Copyright (c) 2008-2011, AQR Capital Management, LLC, Lambda Foundry, Inc. and PyData Development Team
All rights reserved.

Copyright (c) 2011-2023, Open source contributors.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

* Redistributions of source code must retain the above copyright notice, this
  list of conditions and the following disclaimer.

* Redistributions in binary form must reproduce the above copyright notice,
  this list of conditions and the following disclaimer in the documentation
  and/or other materials provided with the distribution.

* Neither the name of the copyright holder nor the names of its
  contributors may be used to endorse or promote products derived from
  this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
Location: /usr/local/lib/python3.12/dist-packages
Requires: numpy, python-dateutil, pytz, tzdata
Required-by: arviz, bigframes, bigquery-magics, bokeh, bqplot, cmdstanpy, cudf-cu12, cufflinks, dask-cuda, dask-cudf-cu12, datasets, db-dtypes, dopamine_rl, fastai, geemap, geopandas, google-colab, gradio, gspread-dataframe, holoviews, libpysal, mizani, mlxtend, pandas-datareader, pandas-gbq, panel, plotnine, prophet, pymc, seaborn, shap, sklearn-pandas, statsmodels, tensorflow_decision_forests, tsfresh, vega-datasets, xarray, yfinance

In order to use any library in Python u need to import this library in your notebook.

In [66]:
import pandas as pd
# command to import pandas library; use alias to ease future access in code.

# DataFrames

## How to manually create a DF?

In [67]:
data = {
    "calories":[420,380,390],
    "duration":[50,40,45]
}
# This is a dictionary object

In [68]:
df = pd.DataFrame(data)
print(df)

   calories  duration
0       420        50
1       380        40
2       390        45

In [69]:
print(type(df))
df

<class 'pandas.core.frame.DataFrame'>

   calories  duration
0       420        50
1       380        40
2       390        45

In [70]:
from google.colab import files

uploaded = files.upload()

# Syntax to upload a file from PC.

Saving student.xlsx to student (2).xlsx

In [71]:
df = pd.read_excel("student.xlsx")   # Command to READ the file. If we have .csv we will use red_csv, for excel .xlsx
df

    id         name  class  mark  gender
0    1     John Deo   Four    75  female
1    2     Max Ruin  Three    85    male
2    3       Arnold  Three    55    male
3    4   Krish Star   Four    60  female
4    5    John Mike   Four    60  female
5    6    Alex John   Four    55    male
6    7  My John Rob  Fifth    78    male
7    8       Asruid   Five    85    male
8    9      Tes Qry    Six    78     NaN
9   10     Big John   Four    55  female
10  11       Ronald    Six    89  female
11  12        Recky    Six    94  female
12  13          Kty  Seven    88  female
13  14         Bigy  Seven    88  female
14  15     Tade Row    NaN    88    male
15  16        Gimmy   Four    88    male
16  17        Tumyu    Six    54    male
17  18        Honny   Five    75    male
18  19        Tinny   Nine    18    male
19  20       Jackly   Nine    65  female
20  21   Babby John   Four    69  female
21  22       Reggid  Seven    55  female
22  23        Herod  Eight    79    male
23  24    Tiddy Now  Seven    78    male
24  25     Giff Tow  Seven    88    male
25  26       Crelea  Seven    79    male
26  27          NaN  Three    81     NaN
27  28    Rojj Base  Seven    86  female
28  29  Tess Played  Seven    55    male
29  30    Reppy Red    Six    79  female
30  31  Marry Toeey   Four    88    male
31  32    Binn Rott  Seven    90  female
32  33    Kenn Rein    Six    96  female
33  34     Gain Toe  Seven    69    male
34  35   Rows Noump    Six    88  female

# top 5 rows

df.head()




# top 10 rows

df.head(10)



# last 5 rows

df.tail()





# last 10 rows

df.tail(10)

In [72]:
df.head()   # first 5rows(default), add number fr specific number of first rows

   id        name  class  mark  gender
0   1    John Deo   Four    75  female
1   2    Max Ruin  Three    85    male
2   3      Arnold  Three    55    male
3   4  Krish Star   Four    60  female
4   5   John Mike   Four    60  female

In [73]:
df.head(10)

   id         name  class  mark  gender
0   1     John Deo   Four    75  female
1   2     Max Ruin  Three    85    male
2   3       Arnold  Three    55    male
3   4   Krish Star   Four    60  female
4   5    John Mike   Four    60  female
5   6    Alex John   Four    55    male
6   7  My John Rob  Fifth    78    male
7   8       Asruid   Five    85    male
8   9      Tes Qry    Six    78     NaN
9  10     Big John   Four    55  female

In [74]:
df.tail()  # last 5rows(default), add number for specific number of last rows.

    id         name  class  mark  gender
30  31  Marry Toeey   Four    88    male
31  32    Binn Rott  Seven    90  female
32  33    Kenn Rein    Six    96  female
33  34     Gain Toe  Seven    69    male
34  35   Rows Noump    Six    88  female

This is importaant as dataset can have thousands of rows

. notation that give access to pandas library. df.head() means go to dataframe and return first 5rows

In [75]:
# random sample data , 1 default, you can specify how many by writing diff number, samples are randomised

df.sample()

   id         name  class  mark gender
6   7  My John Rob  Fifth    78   male

In [76]:
# number of rows and columns, doesn't take the brackets.

df.shape

(35, 5)

In [77]:
# dataset information // will return number of non-null count, number of entries.
# if number of entries and number of non-null count are different, there are some missing values.
# name column has one missing value, 1 student is missing
# gender column has 2 missing values.
# class column has 1 missing value

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35 entries, 0 to 34
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      35 non-null     int64
 1   name    34 non-null     object
 2   class   34 non-null     object
 3   mark    35 non-null     int64
 4   gender  33 non-null     object
dtypes: int64(2), object(3)
memory usage: 1.5+ KB

In [78]:
# name of the columns

df.columns

Index(['id', 'name', 'class', 'mark', 'gender'], dtype='object')

In [79]:
# statistical summary
# this will only show for nuumberic columns
# 50% of data is median value.
df.describe()

              id       mark
count  35.000000  35.000000
mean   18.000000  74.657143
std    10.246951  16.401117
min     1.000000  18.000000
25%     9.500000  62.500000
50%    18.000000  79.000000
75%    26.500000  88.000000
max    35.000000  96.000000

# If std(standard deviation) is equal or higher than mean, there are outliers in your data. Outliers are the data poinnts which are far away then the rest(outside of scope of the data distribution)

In [80]:
# number of rows

len(df)

35

In [81]:
# rows * columns

df.size

175

In [90]:
# datatypes of the columns

df.dtypes

id         int64
name      object
class     object
mark       int64
gender    object
dtype: object

In [83]:
# Counts missing values per column.

df.isnull().sum()

id        0
name      1
class     1
mark      0
gender    2
dtype: int64

In [84]:
# Counts duplicate rows. # eveery column in 2 separate rows must have the exact same values.

df.duplicated().sum()

np.int64(0)

## How to inspect the data subsets
## Subsetting Dataframe

#Slicing Method

In [85]:
df['name']  # It is still a DataFrame so we can apply head() etc.

0        John Deo
1        Max Ruin
2          Arnold
3      Krish Star
4       John Mike
5       Alex John
6     My John Rob
7          Asruid
8         Tes Qry
9        Big John
10         Ronald
11          Recky
12            Kty
13           Bigy
14       Tade Row
15          Gimmy
16          Tumyu
17          Honny
18          Tinny
19         Jackly
20     Babby John
21         Reggid
22          Herod
23      Tiddy Now
24       Giff Tow
25         Crelea
26            NaN
27      Rojj Base
28    Tess Played
29      Reppy Red
30    Marry Toeey
31      Binn Rott
32      Kenn Rein
33       Gain Toe
34     Rows Noump
Name: name, dtype: object

In [86]:
df["mark"].mean()
# average mark

np.float64(74.65714285714286)

In [87]:
# return name and class
# ["name","class"] - it is a LIST OBJECT so this is why we use double [] if we wish to reurn more columns
df[["name","class"]]

           name  class
0      John Deo   Four
1      Max Ruin  Three
2        Arnold  Three
3    Krish Star   Four
4     John Mike   Four
5     Alex John   Four
6   My John Rob  Fifth
7        Asruid   Five
8       Tes Qry    Six
9      Big John   Four
10       Ronald    Six
11        Recky    Six
12          Kty  Seven
13         Bigy  Seven
14     Tade Row    NaN
15        Gimmy   Four
16        Tumyu    Six
17        Honny   Five
18        Tinny   Nine
19       Jackly   Nine
20   Babby John   Four
21       Reggid  Seven
22        Herod  Eight
23    Tiddy Now  Seven
24     Giff Tow  Seven
25       Crelea  Seven
26          NaN  Three
27    Rojj Base  Seven
28  Tess Played  Seven
29    Reppy Red    Six
30  Marry Toeey   Four
31    Binn Rott  Seven
32    Kenn Rein    Six
33     Gain Toe  Seven
34   Rows Noump    Six

In [88]:
df[["id","mark"]] # all previous commands are available as it still a dataframe.

    id  mark
0    1    75
1    2    85
2    3    55
3    4    60
4    5    60
5    6    55
6    7    78
7    8    85
8    9    78
9   10    55
10  11    89
11  12    94
12  13    88
13  14    88
14  15    88
15  16    88
16  17    54
17  18    75
18  19    18
19  20    65
20  21    69
21  22    55
22  23    79
23  24    78
24  25    88
25  26    79
26  27    81
27  28    86
28  29    55
29  30    79
30  31    88
31  32    90
32  33    96
33  34    69
34  35    88

In [91]:
# this will return error because class is a reserved keyword -> after error, restart session. This is why the df[] method is preffered, as it avoids errors.
#also, by using this we cannot return more columns, just one. so it is not effective for above reasons.
df.class

SyntaxError: invalid syntax (ipython-input-1047155908.py, line 3)

In [92]:
#this command will go to name column and return index 0. can be replaced with any index number, to return a different row.

df["name"][0]

'John Deo'

In [93]:
df["gender"][12]

'female'

 ## loc and iloc operator
 - easier way to submit datasets

In [94]:
df.loc[rows,columns(label)]
df.iloc[rows,columns(index)]

# this is the template on how the syntax should look

NameError: name 'rows' is not defined

In [97]:
# Examples using loc and iloc
# Select rows with index 0, 1, and 2 and columns 'name' and 'mark' using loc
print(df.loc[0:2, ["name", "mark"]])

# Select rows with index 0, 1, and 2 and columns at index 1 and 3 using iloc
print(df.iloc[0:3, [1, 3]])

       name  mark
0  John Deo    75
1  Max Ruin    85
2    Arnold    55
       name  mark
0  John Deo    75
1  Max Ruin    85
2    Arnold    55

In [98]:
df.loc[0:5, "name"]
# 0:5 is range of indexes. we can return only an index

0      John Deo
1      Max Ruin
2        Arnold
3    Krish Star
4     John Mike
5     Alex John
Name: name, dtype: object

In [99]:
# What is the mark of the student at index 15
df.loc[15,"mark"]

np.int64(88)

In [100]:
df.loc[0:14,"mark"].mean()
# What is the average mark in this range?

np.float64(75.53333333333333)

In [101]:
# return specific indexes, use [] as it will be a list.
df.loc[[1,4,5], "name"]

1     Max Ruin
4    John Mike
5    Alex John
Name: name, dtype: object

In [102]:
# Return names, class of students at index 1,4,5
df.loc[[1,4,5], ["name","class"]]

        name  class
1   Max Ruin  Three
4  John Mike   Four
5  Alex John   Four

In [103]:
# Return names, class of students at index 1,4,5 ## with iloc we need to use indexes for column names. we use df.info() to find out indexes
df.iloc[[1,4,5], [1,3]]

        name  mark
1   Max Ruin    85
4  John Mike    60
5  Alex John    55

In [104]:
# Use loc and iloc to return name, gender of the students at index 10, 20 30.

df.loc[[10,20,30],["name","gender"]]

           name  gender
10       Ronald  female
20   Babby John  female
30  Marry Toeey    male

In [105]:
df.iloc[[10,20,30],[1,4]]

           name  gender
10       Ronald  female
20   Babby John  female
30  Marry Toeey    male

When using range of values, loc is including start and stop. Iloc will not include stop.

In [106]:
#return first 5 names using iloc
df.iloc[0:5,1]

0      John Deo
1      Max Ruin
2        Arnold
3    Krish Star
4     John Mike
Name: name, dtype: object

In [107]:
#return first 5 names using loc
df.loc[0:4,"name"]

0      John Deo
1      Max Ruin
2        Arnold
3    Krish Star
4     John Mike
Name: name, dtype: object

## Filtering Dataframe

In [108]:
# Return students with mark geater than 90
df["mark"]>90
# This metthod is known as boolean masking

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11     True
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
30    False
31    False
32     True
33    False
34    False
Name: mark, dtype: bool

In [109]:
df[df["mark"]>90]
#This will show the actual students with marks greter than 90

    id       name class  mark  gender
11  12      Recky   Six    94  female
32  33  Kenn Rein   Six    96  female

- Return students with mark less than 50

In [110]:
df[df["mark"]<50]

    id   name class  mark gender
18  19  Tinny  Nine    18   male

- Return first 5 female students.

In [111]:
df[df["gender"]=="female"].head()
# we need to use == not = ## == means to compare & match

    id        name class  mark  gender
0    1    John Deo  Four    75  female
3    4  Krish Star  Four    60  female
4    5   John Mike  Four    60  female
9   10    Big John  Four    55  female
10  11      Ronald   Six    89  female

- Return students at class Four

In [112]:
df[df["class"]=="Four"]

    id         name class  mark  gender
0    1     John Deo  Four    75  female
3    4   Krish Star  Four    60  female
4    5    John Mike  Four    60  female
5    6    Alex John  Four    55    male
9   10     Big John  Four    55  female
15  16        Gimmy  Four    88    male
20  21   Babby John  Four    69  female
30  31  Marry Toeey  Four    88    male

- Return male students at class Four

In [113]:
df[(df["gender"]=="male") & (df["class"]=="Four")]
# each condition needs to be in () the DFs inside needs to be ()

    id         name class  mark gender
5    6    Alex John  Four    55   male
15  16        Gimmy  Four    88   male
30  31  Marry Toeey  Four    88   male

- Return IDs greater than 20 but less than 30

In [114]:
df[(df["id"]>20) & (df["id"]<30)]

    id         name  class  mark  gender
20  21   Babby John   Four    69  female
21  22       Reggid  Seven    55  female
22  23        Herod  Eight    79    male
23  24    Tiddy Now  Seven    78    male
24  25     Giff Tow  Seven    88    male
25  26       Crelea  Seven    79    male
26  27          NaN  Three    81     NaN
27  28    Rojj Base  Seven    86  female
28  29  Tess Played  Seven    55    male

- Return students in class Four using loc operator

In [115]:
df.loc[df["class"]=="Four", :]
## because we are filtering rows, criteria written first.
# : means return all columns

    id         name class  mark  gender
0    1     John Deo  Four    75  female
3    4   Krish Star  Four    60  female
4    5    John Mike  Four    60  female
5    6    Alex John  Four    55    male
9   10     Big John  Four    55  female
15  16        Gimmy  Four    88    male
20  21   Babby John  Four    69  female
30  31  Marry Toeey  Four    88    male

In [116]:
df.iloc[df["class"]=="Four", :]
# We cannot use iloc for boolean masking!

NotImplementedError: iLocation based boolean indexing on an integer type is not available

- Return male students in class Four

In [117]:
df.loc[(df["class"]=="Four") & (df["gender"]=="male"), ["name","class","gender"]]

           name class gender
5     Alex John  Four   male
15        Gimmy  Four   male
30  Marry Toeey  Four   male

- Return students at class Six or class Five

In [118]:
df[(df["class"]=="Five") | (df["class"]=="Six")].sample(5)
 # | symbol is OR in python # , sample(5) will pick 5 random students in class Six OR Five

    id        name class  mark  gender
34  35  Rows Noump   Six    88  female
29  30   Reppy Red   Six    79  female
17  18       Honny  Five    75    male
32  33   Kenn Rein   Six    96  female
7    8      Asruid  Five    85    male

- Average mark across all students

- Average mark across male and female students

- Max and min mark

- Max mark for male and female students

- Average mark for class 'Five'

- Average mark for class 'Six' and male students only

In [119]:
# average mark all students
df["mark"].mean()

np.float64(74.65714285714286)

In [120]:
# Average mark across male and female students
df.loc[(df["gender"] == "male"), "mark"].mean()

np.float64(71.58823529411765)

In [122]:
df.loc[(df["gender"] == "female"), "mark"].mean()

np.float64(77.3125)

In [121]:
# Max and min mark
df["mark"].max()
df["mark"].min()

18

In [123]:
df["mark"].max()

96

In [124]:
# Max mark for male and female students
df[df['gender'] == 'male']['mark'].max()
df[df['gender'] == 'female']['mark'].max()

96

In [125]:
# Max mark for male students without groupby
max_male_mark = df[df['gender'] == 'male']['mark'].max()
print(f"Maximum mark for male students: {max_male_mark}")

# Max mark for female students without groupby
max_female_mark = df[df['gender'] == 'female']['mark'].max()
print(f"Maximum mark for female students: {max_female_mark}")

Maximum mark for male students: 88
Maximum mark for female students: 96

In [126]:
# Average mark for class 'Five'
df[df["class"]=="Five"]["mark"].mean()

np.float64(80.0)

In [127]:
df.loc[df["class"]=="Five","mark"].mean()

np.float64(80.0)

In [128]:
# Average mark for class 'Six' and male students only
df[(df["class"]=="Six") & (df["gender"]=="male")]["mark"].mean()

np.float64(54.0)

In [129]:
df.loc[(df["class"]=="Six") & (df["gender"]=="male"), "mark"].mean()

np.float64(54.0)

## How to sort results

In [130]:
df.sort_values(by="mark")
# can use any column to sort by
# default sorting is ascending

    id         name  class  mark  gender
18  19        Tinny   Nine    18    male
16  17        Tumyu    Six    54    male
2    3       Arnold  Three    55    male
5    6    Alex John   Four    55    male
28  29  Tess Played  Seven    55    male
21  22       Reggid  Seven    55  female
9   10     Big John   Four    55  female
4    5    John Mike   Four    60  female
3    4   Krish Star   Four    60  female
19  20       Jackly   Nine    65  female
20  21   Babby John   Four    69  female
33  34     Gain Toe  Seven    69    male
0    1     John Deo   Four    75  female
17  18        Honny   Five    75    male
8    9      Tes Qry    Six    78     NaN
23  24    Tiddy Now  Seven    78    male
6    7  My John Rob  Fifth    78    male
22  23        Herod  Eight    79    male
29  30    Reppy Red    Six    79  female
25  26       Crelea  Seven    79    male
26  27          NaN  Three    81     NaN
1    2     Max Ruin  Three    85    male
7    8       Asruid   Five    85    male
27  28    Rojj Base  Seven    86  female
12  13          Kty  Seven    88  female
24  25     Giff Tow  Seven    88    male
15  16        Gimmy   Four    88    male
14  15     Tade Row    NaN    88    male
30  31  Marry Toeey   Four    88    male
13  14         Bigy  Seven    88  female
34  35   Rows Noump    Six    88  female
10  11       Ronald    Six    89  female
31  32    Binn Rott  Seven    90  female
11  12        Recky    Six    94  female
32  33    Kenn Rein    Six    96  female

In [131]:
df.sort_values(by="mark", ascending=False)
#Python doesn't have Descending sort so we need to use ascending=False

    id         name  class  mark  gender
32  33    Kenn Rein    Six    96  female
11  12        Recky    Six    94  female
31  32    Binn Rott  Seven    90  female
10  11       Ronald    Six    89  female
30  31  Marry Toeey   Four    88    male
34  35   Rows Noump    Six    88  female
24  25     Giff Tow  Seven    88    male
14  15     Tade Row    NaN    88    male
15  16        Gimmy   Four    88    male
12  13          Kty  Seven    88  female
13  14         Bigy  Seven    88  female
27  28    Rojj Base  Seven    86  female
7    8       Asruid   Five    85    male
1    2     Max Ruin  Three    85    male
26  27          NaN  Three    81     NaN
29  30    Reppy Red    Six    79  female
25  26       Crelea  Seven    79    male
22  23        Herod  Eight    79    male
6    7  My John Rob  Fifth    78    male
23  24    Tiddy Now  Seven    78    male
8    9      Tes Qry    Six    78     NaN
17  18        Honny   Five    75    male
0    1     John Deo   Four    75  female
33  34     Gain Toe  Seven    69    male
20  21   Babby John   Four    69  female
19  20       Jackly   Nine    65  female
3    4   Krish Star   Four    60  female
4    5    John Mike   Four    60  female
2    3       Arnold  Three    55    male
5    6    Alex John   Four    55    male
9   10     Big John   Four    55  female
21  22       Reggid  Seven    55  female
28  29  Tess Played  Seven    55    male
16  17        Tumyu    Six    54    male
18  19        Tinny   Nine    18    male

In [132]:
df.loc[df["gender"]=="male", :].sort_values(by="name").head()
# In this case we filter by gender and sort values by name

    id       name  class  mark gender
5    6  Alex John   Four    55   male
2    3     Arnold  Three    55   male
7    8     Asruid   Five    85   male
25  26     Crelea  Seven    79   male
33  34   Gain Toe  Seven    69   male

In [133]:
# return student who are female or at class seven
df[(df["gender"]=="female") | (df["class"]=="Seven")].sort_values(by="mark")

    id         name  class  mark  gender
9   10     Big John   Four    55  female
21  22       Reggid  Seven    55  female
28  29  Tess Played  Seven    55    male
3    4   Krish Star   Four    60  female
4    5    John Mike   Four    60  female
19  20       Jackly   Nine    65  female
20  21   Babby John   Four    69  female
33  34     Gain Toe  Seven    69    male
0    1     John Deo   Four    75  female
23  24    Tiddy Now  Seven    78    male
29  30    Reppy Red    Six    79  female
25  26       Crelea  Seven    79    male
27  28    Rojj Base  Seven    86  female
24  25     Giff Tow  Seven    88    male
12  13          Kty  Seven    88  female
13  14         Bigy  Seven    88  female
34  35   Rows Noump    Six    88  female
10  11       Ronald    Six    89  female
31  32    Binn Rott  Seven    90  female
11  12        Recky    Six    94  female
32  33    Kenn Rein    Six    96  female

In [134]:
# Write code to find information of female students who are above the classroom average. Sort the results in descending order.
df[(df["gender"]=="female")&(df["mark"]>df["mark"].mean())].sort_values(by="mark",ascending=False)

# 1st step: - filter by gender: df[(df["gender"]=="female")
# 2nd step: filter by class average &(df["mark"]>df["mark"].mean())]
# 3rd step: sort the values as descending .sort_values(by="mark",ascending=False)

    id        name  class  mark  gender
32  33   Kenn Rein    Six    96  female
11  12       Recky    Six    94  female
31  32   Binn Rott  Seven    90  female
10  11      Ronald    Six    89  female
34  35  Rows Noump    Six    88  female
12  13         Kty  Seven    88  female
13  14        Bigy  Seven    88  female
27  28   Rojj Base  Seven    86  female
29  30   Reppy Red    Six    79  female
0    1    John Deo   Four    75  female

In [135]:
df["mark"].mean()

np.float64(74.65714285714286)

In [136]:
average = df["mark"].mean()
# creating average variable , df.loc version

df.loc[(df["gender"]=="female") & (df["mark"]>average) , ["name","mark", "gender"]].sort_values(by="mark", ascending=False)

          name  mark  gender
32   Kenn Rein    96  female
11       Recky    94  female
31   Binn Rott    90  female
10      Ronald    89  female
34  Rows Noump    88  female
12         Kty    88  female
13        Bigy    88  female
27   Rojj Base    86  female
29   Reppy Red    79  female
0     John Deo    75  female

In [137]:
df.loc[(df["gender"]=="female") & (df["mark"] > df["mark"].mean()), ["name","mark", "gender"]].sort_values(by="mark", ascending=False)

# df.loc version without average variable.

          name  mark  gender
32   Kenn Rein    96  female
11       Recky    94  female
31   Binn Rott    90  female
10      Ronald    89  female
34  Rows Noump    88  female
12         Kty    88  female
13        Bigy    88  female
27   Rojj Base    86  female
29   Reppy Red    79  female
0     John Deo    75  female

## Value_counts
Show number of occurences

In [138]:
## How many male and female students are there?
df["gender"].value_counts()

gender
male      17
female    16
Name: count, dtype: int64

In [139]:
## Class and number of student
df["class"].value_counts()

class
Seven    10
Four      8
Six       7
Three     3
Nine      2
Five      2
Fifth     1
Eight     1
Name: count, dtype: int64

In [140]:
df.loc[5]

id                6
name      Alex John
class          Four
mark             55
gender         male
Name: 5, dtype: object

In [141]:
df.isnull()

       id   name  class   mark  gender
0   False  False  False  False   False
1   False  False  False  False   False
2   False  False  False  False   False
3   False  False  False  False   False
4   False  False  False  False   False
5   False  False  False  False   False
6   False  False  False  False   False
7   False  False  False  False   False
8   False  False  False  False    True
9   False  False  False  False   False
10  False  False  False  False   False
11  False  False  False  False   False
12  False  False  False  False   False
13  False  False  False  False   False
14  False  False   True  False   False
15  False  False  False  False   False
16  False  False  False  False   False
17  False  False  False  False   False
18  False  False  False  False   False
19  False  False  False  False   False
20  False  False  False  False   False
21  False  False  False  False   False
22  False  False  False  False   False
23  False  False  False  False   False
24  False  False  False  False   False
25  False  False  False  False   False
26  False   True  False  False    True
27  False  False  False  False   False
28  False  False  False  False   False
29  False  False  False  False   False
30  False  False  False  False   False
31  False  False  False  False   False
32  False  False  False  False   False
33  False  False  False  False   False
34  False  False  False  False   False

In [148]:
# Rename the item name column to item_name
df.rename(columns={"item name":"item_name"}, inplace=True)

In [149]:
# Assign dataframe named `df` out of the following list of dictionaries
items = [
    {"item name": "USB cable", "price": "$10.99", "type": "USB C to USB C"},
    {"item name": "USB cable", "price": "$10.99", "type": "USB A to USB C"},
    {"item name": "Batteries", "price": "$9.99", "type": "AA"},
    {"item name": "Batteries", "price": "$8.99", "type": "AAA"},
    {"item name": "Mouse", "price": "$12.99", "type": "Wireless USB"},
]
df

    id         name  class  mark  gender  units_sold
0    1     John Deo   Four    75  female          41
1    2     Max Ruin  Three    85    male         113
2    3       Arnold  Three    55    male          54
3    4   Krish Star   Four    60  female          35
4    5    John Mike   Four    60  female          22
5    6    Alex John   Four    55    male          10
6    7  My John Rob  Fifth    78    male           5
7    8       Asruid   Five    85    male          18
8    9      Tes Qry    Six    78     NaN          30
9   10     Big John   Four    55  female           9
10  11       Ronald    Six    89  female          45
11  12        Recky    Six    94  female          50
12  13          Kty  Seven    88  female          12
13  14         Bigy  Seven    88  female          25
14  15     Tade Row    NaN    88    male          33
15  16        Gimmy   Four    88    male           8
16  17        Tumyu    Six    54    male          15
17  18        Honny   Five    75    male          28
18  19        Tinny   Nine    18    male           3
19  20       Jackly   Nine    65  female          40
20  21   Babby John   Four    69  female          21
21  22       Reggid  Seven    55  female          14
22  23        Herod  Eight    79    male          19
23  24    Tiddy Now  Seven    78    male           7
24  25     Giff Tow  Seven    88    male          26
25  26       Crelea  Seven    79    male          31
26  27          NaN  Three    81     NaN           6
27  28    Rojj Base  Seven    86  female          29
28  29  Tess Played  Seven    55    male           4
29  30    Reppy Red    Six    79  female          20
30  31  Marry Toeey   Four    88    male          36
31  32    Binn Rott  Seven    90  female           1
32  33    Kenn Rein    Six    96  female          38
33  34     Gain Toe  Seven    69    male          16
34  35   Rows Noump    Six    88  female          24

In [151]:
# Add a column named units_sold to this dataframe and assign values (example with placeholder values)
df["units_sold"] = [41, 113, 54, 35, 22, 10, 5, 18, 30, 9, 45, 50, 12, 25, 33, 8, 15, 28, 3, 40, 21, 14, 19, 7, 26, 31, 6, 29, 4, 20, 36, 1, 38, 16, 24]
print(df.head()) # Print the head to show the new column

   id        name  class  mark  gender  units_sold
0   1    John Deo   Four    75  female          41
1   2    Max Ruin  Three    85    male         113
2   3      Arnold  Three    55    male          54
3   4  Krish Star   Four    60  female          35
4   5   John Mike   Four    60  female          22

In [153]:
# Assign dataframe named `df` out of the following list of dictionaries
items = [
    {"item name": "USB cable", "price": "$10.99", "type": "USB C to USB C"},
    {"item name": "USB cable", "price": "$10.99", "type": "USB A to USB C"},
    {"item name": "Batteries", "price": "$9.99", "type": "AA"},
    {"item name": "Batteries", "price": "$8.99", "type": "AAA"},
    {"item name": "Mouse", "price": "$12.99", "type": "Wireless USB"},
]

# Create a new DataFrame from the items list
df_items = pd.DataFrame(items)

# Convert the price column into a float data type. First replace $ and then convert to float.
df_items["price"] = df_items["price"].str.replace("$", "").astype(float)

# Display the updated DataFrame
print(df_items)

   item name  price            type
0  USB cable  10.99  USB C to USB C
1  USB cable  10.99  USB A to USB C
2  Batteries   9.99              AA
3  Batteries   8.99             AAA
4      Mouse  12.99    Wireless USB

In [156]:
#Create a new column named is_automatic that holds a Boolean if that given vehicle is an automatic transmission or not.
df_items["is_automatic"] = df_items["type"].str.contains("Automatic")